import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const languages = {
    TR: {
        home: 'Anasayfa',
        about: 'Hakkımızda',
        services: 'Katalog',
        faq: 'S.S.S',
        contact: 'İletişim',
        heroTitle: 'ÇE & Fİ',
        heroSub: "Türkiye'nin En Prestijli Toptan Tekstil Koleksiyonu",
        explore: 'Koleksiyonu Keşfet',
        offer: 'Toptan Teklif Al',
        categories: 'Ana Koleksiyonlar',
        wholesale: 'Toptan Satış',
        address: 'Adres',
        phone: 'Telefon',
        email: 'E-Posta',
        ourStory: 'Hikayemiz',
        heritage: 'Mirasımız',
        experience: 'Yıllık Tecrübe',
        dealers: 'Müşteri Sayısı',
        productTypes: 'Ürün Çeşidi',
        catalog: 'Katalog',
        all: 'Hepsi',
        reachUs: 'Bize Ulaşın',
        sendMessage: 'Mesajı Gönder',
        faqTitle: 'Sıkça Sorulan Sorular',
        formName: 'ADINIZ',
        formFirm: 'FİRMA',
        formMessage: 'MESAJINIZ',
        commentsTitle: 'Müşteri Deneyimleri',
        noComments: 'Henüz yorum yapılmamış. İlk yorumu sen yap!',
        leaveComment: 'Yorum Bırakın',
        commentPlaceholder: 'Sizden duymak istiyoruz...',
        commentSubmit: 'Yorumu Gönder',
        commentPending: 'Yorumunuz onay bekliyor.',
        commentName: 'Adınız',
        error404Title: '404 - Sayfa Bulunamadı',
        error404Message: 'Aradığınız sayfa taşınmış veya hiç var olmamış olabilir.',
        backToHome: 'ANASAYFAYA DÖN',
        foundersTitle: 'Kurucularımız',
        founderTitle: 'Kurucu Ortak',
        founderCetin: 'Çetin Kızılkaya',
        founderMehmet: 'Mehmet Oturmak',
        aboutMainText: "Çetin Ticaret ve Fidan Ticaret olarak 2009 yılında Diyarbakır Sur'daki ilk mağazalarımızla yola çıktık. 2022 yılında güçlerimizi birleştirerek Çe&Fi Tekstil markasını oluşturduk. Bugün modern vizyonumuzla tekstil dünyasında lüksü ve kaliteyi temsil ediyoruz.",
        timelineTitle: 'Kilometre Taşlarımız',
        timeline2009: 'KURULUŞ — İlk mağazalar açıldı (Diyarbakır Sur).',
        timeline2015: 'Bölgesel büyüme ve tedarik ağının genişlemesi sağlandı.',
        timeline2022: 'BİRLEŞME — Çe&Fi Tekstil adı altında güçler birleştirildi.',
        timeline2024: 'YENİ MAĞAZA — Kantar Toptancılar Sitesi karşısı Yıldız Office’e taşınıldı.',
        timelineFuture: 'Gelecek: Sürdürülebilir üretim ve küresel büyüme hedefleniyor.',
        catCeyiz: 'Çeyiz',
        catCocuk: 'Çocuk & Bebek',
        catIcGiyim: 'İç Giyim',
        cartTitle: 'Sepetim',
        addToCart: 'Sepete Ekle',
        cartEmpty: 'Sepetiniz henüz boş.',
        cartTotal: 'Toplam Tutar',
        cartCheckout: 'Siparişi Tamamla',
        searchPlaceholder: 'Ürün ara...',
        sortTitle: 'Sırala',
        filterTitle: 'Filtrele',
        price: 'Fiyat',
        joinUs: 'BİZE KATILIN'
    },
    EN: {
        home: 'Home',
        about: 'About Us',
        services: 'Catalog',
        faq: 'FAQ',
        contact: 'Contact',
        heroTitle: 'CE & FI',
        heroSub: "Turkey's Most Prestigious Wholesale Textile Collection",
        explore: 'Explore Collection',
        offer: 'Get Wholesale Offer',
        categories: 'Main Collections',
        wholesale: 'Wholesale Center',
        address: 'Address',
        phone: 'Phone',
        email: 'E-Mail',
        ourStory: 'Our Story',
        heritage: 'Heritage',
        experience: 'Years Experience',
        dealers: 'Happy Customers',
        productTypes: 'Product Types',
        catalog: 'Catalog',
        all: 'All',
        reachUs: 'Reach Us',
        sendMessage: 'Send Message',
        faqTitle: 'Frequently Asked Questions',
        formName: 'YOUR NAME',
        formFirm: 'COMPANY',
        formMessage: 'YOUR MESSAGE',
        commentsTitle: 'Customer Experiences',
        noComments: 'No comments yet. Be the first to comment!',
        leaveComment: 'Leave a Comment',
        commentPlaceholder: 'We want to hear from you...',
        commentSubmit: 'Submit Comment',
        commentPending: 'Your comment is awaiting approval.',
        commentName: 'Your Name',
        error404Title: '404 - Page Not Found',
        error404Message: 'The page you are looking for might have been moved or never existed.',
        backToHome: 'BACK TO HOME',
        foundersTitle: 'Our Founders',
        founderTitle: 'Co-Founder',
        founderCetin: 'Çetin Kızılkaya',
        founderMehmet: 'Mehmet Oturmak',
        aboutMainText: "Starting as Çetin and Fidan Ticaret in 2009 with our first stores in Diyarbakır, we merged in 2022 to form Çe&Fi Tekstil. Today, we represent luxury and quality with our modern vision.",
        timelineTitle: 'Our Milestones',
        timeline2009: 'FOUNDATION — First stores opened in Diyarbakır Sur.',
        timeline2015: 'Regional growth and expansion of the supply network.',
        timeline2022: 'MERGER — United under the Çe&Fi Tekstil brand.',
        timeline2024: 'NEW STORE — Moved to Yıldız Office, new showroom opened.',
        timelineFuture: 'Future: Targeting sustainable production and global growth.',
        catCeyiz: 'Dowry',
        catCocuk: 'Kids & Baby',
        catIcGiyim: 'Underwear',
        cartTitle: 'My Cart',
        addToCart: 'Add to Cart',
        cartEmpty: 'Your cart is empty.',
        cartTotal: 'Total Amount',
        cartCheckout: 'Complete Order',
        searchPlaceholder: 'Search products...',
        sortTitle: 'Sort',
        filterTitle: 'Filter',
        price: 'Price',
        joinUs: 'JOIN US'
    },
    KU: {
        home: 'Mala Serî',
        about: 'Derbarê Me',
        services: 'Katalog',
        faq: 'P.S.B',
        contact: 'Têkilî',
        heroTitle: 'ÇE & Fİ',
        heroSub: "Koleksiyona Tekstîlê ya Toptan a Herî Bi Prestîj a Tirkiyeyê",
        explore: 'Koleksiyonê Keşf Bike',
        offer: 'Pêşniyara Toptan Bigire',
        categories: 'Koleksiyonên Sereke',
        wholesale: 'Navenda Toptan',
        address: 'Navnîşan',
        phone: 'Telefon',
        email: 'E-Posta',
        ourStory: 'Çîroka Me',
        heritage: 'Mîrasa Me',
        experience: 'Tecrûbeya Salan',
        dealers: 'Hejmara Mişteriyan',
        productTypes: 'Cureyên Berhemê',
        catalog: 'Katalog',
        all: 'Hemû',
        reachUs: 'Bi Me Re Têkilî Biynin',
        sendMessage: 'Mesajê Bişîne',
        faqTitle: 'Pirsên Herî Pir Tên Pirsîn',
        formName: 'NAVÊ WE',
        formFirm: 'FİRMA',
        formMessage: 'MESAJÊ WE',
        commentsTitle: 'Tecrubeyên Xerîdar',
        noComments: 'Hîn şîrove nehatine kirin. Şîroveya yekem tu bike!',
        leaveComment: 'Şîroveyek Bihêle',
        commentPlaceholder: 'Em dixwazin ji we bibîzin...',
        commentSubmit: 'Şîroveyê Bişîne',
        commentPending: 'Şîroveya we li benda pejirandinê ye.',
        commentName: 'Navê We',
        error404Title: '404 - Rûpel Neyê Dîtin',
        error404Message: 'Dibe ku rûpela ku hûn lê digerin hatibe barkirin an jî qet tune be.',
        backToHome: 'VEGERE SER SEREKE',
        foundersTitle: 'Avakarên Me',
        founderTitle: 'Hev-Avakar',
        founderCetin: 'Çetin Kızılkaya',
        founderMehmet: 'Mehmet Oturmak',
        aboutMainText: "Çetin Ticaret û Fidan Ticaret di sala 2009an de li Sûra Amedê dest bi xebatê kirin. Di sala 2022an de em bûn yek û markaya Çe&Fi Tekstîl ava kir. Îro em bi vîzyona xwe ya nûjen di cîhana tekstîlê de luks û kalîteyê temsîl dikin.",
        timelineTitle: 'Gavên Me Yên Girîng',
        timeline2009: 'AVAKIRIN — Mağazayên pêşîn li Sûra Amedê hatin vekirin.',
        timeline2015: 'Mezinbûna herêmî û berfirehkirina tora dabînkirinê.',
        timeline2022: 'YEKGIRTIN — Di bin navê Çe&Fi Tekstîl de hêz hatin yekkirin.',
        timeline2024: 'CIHÊ NÛ — Veguhastin Yıldız Office-ê, beşa çeyizê hat avakirin.',
        timelineFuture: 'Pêşeroj: Hilberîna domdar û mezinbûna gerdûnî tê armanc kirin.',
        catCeyiz: 'Çeyiz',
        catCocuk: 'Zarok & Pitik',
        catIcGiyim: 'Kincên Hundir',
        cartTitle: 'Sepeta Min',
        addToCart: 'Tevlî Sepetê Bike',
        cartEmpty: 'Sepeta we vala ye.',
        cartTotal: 'Mîqdara Giştî',
        cartCheckout: 'Siparîşê Temam Bike',
        searchPlaceholder: 'Berhem bigere...',
        sortTitle: 'Rêz Bike',
        filterTitle: 'Parzûn Bike',
        price: 'Bihat',
        joinUs: 'TEVLI ME BIBIN'
    }
};

export const LanguageProvider = ({ children }) => {
    const [lang, setLang] = useState('TR');
    const t = languages[lang];

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
